// 200 specs blog Recacor — données structurées (templates appliqués dans generate-blog-articles.mjs).

export const VILLES_VL = [
  { ville: "Montpellier", slug: "pneus-voiture-montpellier", distance: "10 min", axe: "RN113 ou A709", cp: "34000", titre: "Pneus Voiture à Montpellier — Garage Recacor Le Crès", metaTitle: "Pneus Voiture Montpellier | Garage Recacor à 10 min" },
  { ville: "Lattes", slug: "pneus-lattes", distance: "12 min", axe: "contournement Est", cp: "34970", titre: "Pneus Pas Chers à Lattes — Montage & Équilibrage", metaTitle: "Pneus Lattes — Montage Rapide, Prix Discount" },
  { ville: "Mauguio", slug: "pneus-mauguio", distance: "10 min", axe: "D189", cp: "34130", titre: "Changer ses Pneus à Mauguio — Recacor Le Crès", metaTitle: "Pneus Mauguio | Recacor — 15 min, Sans Rendez-vous" },
  { ville: "Vendargues", slug: "pneus-vendargues", distance: "5 min", axe: "route de Nîmes", cp: "34740", titre: "Garage Pneus à Vendargues — Spécialiste Pneumatique", metaTitle: "Pneus Vendargues | Recacor Le Crès — Spécialiste" },
  { ville: "Castelnau-le-Lez", slug: "pneus-castelnau-le-lez", distance: "5 min", axe: "D66", cp: "34170", titre: "Pneus Voiture Castelnau-le-Lez — Prix & Montage", metaTitle: "Pneus Castelnau-le-Lez | Garage Recacor" },
  { ville: "Jacou", slug: "pneus-jacou", distance: "10 min", axe: "D172", cp: "34830", titre: "Pneus à Jacou — Garage Spécialiste Hérault", metaTitle: "Pneus Jacou — Recacor Le Crès à 10 min" },
  { ville: "Clapiers", slug: "pneus-clapiers", distance: "12 min", axe: "D65", cp: "34830", titre: "Changement Pneus Clapiers — Recacor Le Crès", metaTitle: "Pneus Clapiers — Garage Recacor Hérault" },
  { ville: "Saint-Clément-de-Rivière", slug: "pneus-saint-clement-de-riviere", distance: "18 min", axe: "D17", cp: "34980", titre: "Pneus à Saint-Clément-de-Rivière — Spécialiste Pneus", metaTitle: "Pneus Saint-Clément-de-Rivière | Recacor" },
  { ville: "Prades-le-Lez", slug: "pneus-prades-le-lez", distance: "15 min", axe: "D17", cp: "34730", titre: "Pneus Prades-le-Lez — Montage Rapide & Prix Discount", metaTitle: "Pneus Prades-le-Lez | Recacor Le Crès" },
  { ville: "Saint-Gély-du-Fesc", slug: "pneus-saint-gely-du-fesc", distance: "20 min", axe: "D986", cp: "34980", titre: "Pneus Saint-Gély-du-Fesc — Recacor Votre Spécialiste", metaTitle: "Pneus Saint-Gély-du-Fesc | Garage Recacor" },
  { ville: "Grabels", slug: "pneus-grabels", distance: "20 min", axe: "A750/contournement", cp: "34790", titre: "Garage Pneus à Grabels — Le Crès à 20 min", metaTitle: "Pneus Grabels — Recacor Le Crès Hérault" },
  { ville: "Juvignac", slug: "pneus-juvignac", distance: "20 min", axe: "A750", cp: "34990", titre: "Pneus Voiture Juvignac — Recacor Spécialiste Pneus", metaTitle: "Pneus Juvignac — Recacor, Prix Discount" },
  { ville: "Lunel", slug: "pneus-lunel", distance: "20 min", axe: "A9", cp: "34400", titre: "Pneus à Lunel — Montage Rapide & Équilibrage", metaTitle: "Pneus Lunel — Recacor Le Crès, Sans RDV" },
  { ville: "Lunel-Viel", slug: "pneus-lunel-viel", distance: "18 min", axe: "RN113", cp: "34400", titre: "Pneus Lunel-Viel — Garage Pneumatique Hérault", metaTitle: "Pneus Lunel-Viel | Recacor Spécialiste" },
  { ville: "Baillargues", slug: "pneus-baillargues", distance: "8 min", axe: "RN113", cp: "34670", titre: "Changement Pneus Baillargues — Service Rapide", metaTitle: "Pneus Baillargues | Recacor Le Crès" },
  { ville: "Mudaison", slug: "pneus-mudaison", distance: "10 min", axe: "D610", cp: "34130", titre: "Pneus Mudaison — Spécialiste Pneus Hérault", metaTitle: "Pneus Mudaison — Recacor, 15 min Le Crès" },
  { ville: "Lansargues", slug: "pneus-lansargues", distance: "12 min", axe: "D24", cp: "34130", titre: "Pneus Lansargues — Recacor Votre Garage de Confiance", metaTitle: "Pneus Lansargues | Garage Recacor Hérault" },
  { ville: "Saint-Aunès", slug: "pneus-saint-aunes", distance: "5 min", axe: "RN113", cp: "34130", titre: "Garage Pneus Saint-Aunès — Prix & Délais", metaTitle: "Pneus Saint-Aunès — Recacor Le Crès" },
  { ville: "Pérols", slug: "pneus-perols", distance: "15 min", axe: "A9", cp: "34470", titre: "Pneus Pérols — Montage & Équilibrage Sans Attente", metaTitle: "Pneus Pérols | Recacor Le Crès à 15 min" },
  { ville: "Palavas-les-Flots", slug: "pneus-palavas-les-flots", distance: "20 min", axe: "D986", cp: "34250", titre: "Pneus Palavas-les-Flots — Recacor, Service Rapide", metaTitle: "Pneus Palavas | Recacor — Garage Hérault" },
  { ville: "Carnon", slug: "pneus-carnon", distance: "18 min", axe: "D62", cp: "34280", titre: "Pneus Carnon — Garage Pneumatique Le Crès", metaTitle: "Pneus Carnon — Recacor Le Crès, Hérault" },
  { ville: "Mireval", slug: "pneus-mireval", distance: "25 min", axe: "A9", cp: "34110", titre: "Pneus Mireval — Spécialiste Pneus Recacor", metaTitle: "Pneus Mireval | Recacor Garage Pneus" },
  { ville: "Vic-la-Gardiole", slug: "pneus-vic-la-gardiole", distance: "25 min", axe: "A9", cp: "34110", titre: "Pneus Vic-la-Gardiole — Recacor à 25 min", metaTitle: "Pneus Vic-la-Gardiole | Recacor Le Crès" },
  { ville: "Gigean", slug: "pneus-gigean", distance: "30 min", axe: "A9", cp: "34770", titre: "Pneus Gigean — Montage Rapide Recacor", metaTitle: "Pneus Gigean | Recacor Spécialiste Hérault" },
  { ville: "Mèze", slug: "pneus-meze", distance: "35 min", axe: "A9 puis D613", cp: "34140", titre: "Pneus Mèze — Spécialiste Pneumatique Hérault", metaTitle: "Pneus Mèze | Recacor Garage Le Crès" },
  { ville: "Pignan", slug: "pneus-pignan", distance: "25 min", axe: "A709", cp: "34570", titre: "Pneus Pignan — Recacor Votre Garage Pneus", metaTitle: "Pneus Pignan — Recacor, Prix Discount" },
  { ville: "Lavérune", slug: "pneus-laverune", distance: "20 min", axe: "A709", cp: "34880", titre: "Pneus Lavérune — Montage & Équilibrage", metaTitle: "Pneus Lavérune | Recacor Le Crès Hérault" },
  { ville: "Saint-Georges-d'Orques", slug: "pneus-saint-georges-dorques", distance: "20 min", axe: "A750", cp: "34680", titre: "Pneus Saint-Georges-d'Orques — Recacor", metaTitle: "Pneus Saint-Georges-d'Orques | Recacor" },
  { ville: "Saussan", slug: "pneus-saussan", distance: "22 min", axe: "A709", cp: "34570", titre: "Pneus Saussan — Garage Pneus Hérault", metaTitle: "Pneus Saussan | Recacor Le Crès" },
  { ville: "Cournonsec", slug: "pneus-cournonsec", distance: "22 min", axe: "A709", cp: "34660", titre: "Pneus Cournonsec — Spécialiste Pneus Le Crès", metaTitle: "Pneus Cournonsec | Recacor Hérault" },
  { ville: "Guzargues", slug: "pneus-guzargues", distance: "15 min", axe: "D17", cp: "34820", titre: "Pneus Guzargues — Recacor Votre Spécialiste", metaTitle: "Pneus Guzargues | Recacor Le Crès" },
  { ville: "Assas", slug: "pneus-assas", distance: "15 min", axe: "D17", cp: "34820", titre: "Pneus Assas — Montage Rapide & Prix Discount", metaTitle: "Pneus Assas — Recacor Le Crès Hérault" },
  { ville: "Restinclières", slug: "pneus-restinclieres", distance: "10 min", axe: "D610", cp: "34160", titre: "Pneus Restinclières — Garage Spécialiste Pneus", metaTitle: "Pneus Restinclières | Recacor" },
  { ville: "Teyran", slug: "pneus-teyran", distance: "10 min", axe: "D68", cp: "34820", titre: "Pneus Teyran — Recacor, Sans Rendez-vous", metaTitle: "Pneus Teyran | Recacor Le Crès, Hérault" },
  { ville: "Saint-Drézéry", slug: "pneus-saint-drezery", distance: "15 min", axe: "D610", cp: "34160", titre: "Pneus Saint-Drézéry — Spécialiste Pneumatique", metaTitle: "Pneus Saint-Drézéry | Recacor" },
  { ville: "Sussargues", slug: "pneus-sussargues", distance: "12 min", axe: "D610", cp: "34160", titre: "Pneus Sussargues — Garage Pneus Hérault", metaTitle: "Pneus Sussargues | Recacor Le Crès" },
  { ville: "Valergues", slug: "pneus-valergues", distance: "12 min", axe: "D26", cp: "34130", titre: "Pneus Valergues — Recacor Votre Garage", metaTitle: "Pneus Valergues | Recacor Hérault" },
  { ville: "Beaulieu", slug: "pneus-beaulieu", distance: "15 min", axe: "D610", cp: "34160", titre: "Pneus Beaulieu — Montage Rapide Le Crès", metaTitle: "Pneus Beaulieu — Recacor Le Crès" },
  { ville: "Saint-Just", slug: "pneus-saint-just", distance: "15 min", axe: "RN113", cp: "34400", titre: "Pneus Saint-Just — Recacor Spécialiste Hérault", metaTitle: "Pneus Saint-Just | Recacor Le Crès" },
  { ville: "Saint-Geniès-des-Mourgues", slug: "pneus-saint-genies-des-mourgues", distance: "10 min", axe: "RN113", cp: "34160", titre: "Pneus Saint-Geniès-des-Mourgues — Recacor", metaTitle: "Pneus Saint-Geniès-des-Mourgues" },
  { ville: "Saturargues", slug: "pneus-saturargues", distance: "20 min", axe: "RN113", cp: "34400", titre: "Pneus Saturargues — Garage Pneumatique Hérault", metaTitle: "Pneus Saturargues | Recacor" },
  { ville: "Boisseron", slug: "pneus-boisseron", distance: "22 min", axe: "RN113", cp: "34160", titre: "Pneus Boisseron — Spécialiste Pneus Le Crès", metaTitle: "Pneus Boisseron | Recacor Le Crès" },
  { ville: "Villetelle", slug: "pneus-villetelle", distance: "22 min", axe: "RN113", cp: "34400", titre: "Pneus Villetelle — Recacor Garage Hérault", metaTitle: "Pneus Villetelle | Recacor Hérault" },
  { ville: "Gallargues-le-Montueux", slug: "pneus-gallargues", distance: "25 min", axe: "A9", cp: "30660", titre: "Pneus Gallargues-le-Montueux — Recacor", metaTitle: "Pneus Gallargues | Recacor Le Crès" },
  { ville: "Candillargues", slug: "pneus-candillargues", distance: "12 min", axe: "D24", cp: "34130", titre: "Pneus Candillargues — Garage Pneus Hérault", metaTitle: "Pneus Candillargues | Recacor" },
  { ville: "Saint-Nazaire-de-Pézan", slug: "pneus-saint-nazaire-de-pezan", distance: "15 min", axe: "D24", cp: "34400", titre: "Pneus Saint-Nazaire-de-Pézan — Recacor", metaTitle: "Pneus Saint-Nazaire-de-Pézan | Recacor" },
  { ville: "Montbazin", slug: "pneus-montbazin", distance: "30 min", axe: "A9", cp: "34560", titre: "Pneus Montbazin — Recacor Spécialiste Pneus", metaTitle: "Pneus Montbazin | Recacor Le Crès" },
  { ville: "Cournonterral", slug: "pneus-cournonterral", distance: "25 min", axe: "A709", cp: "34660", titre: "Pneus Cournonterral — Garage Pneus Hérault", metaTitle: "Pneus Cournonterral | Recacor" },
  { ville: "Murviel-lès-Montpellier", slug: "pneus-murviel-les-montpellier", distance: "25 min", axe: "A709", cp: "34570", titre: "Pneus Murviel-lès-Montpellier — Recacor", metaTitle: "Pneus Murviel-lès-Montpellier | Recacor" },
  { ville: "Villeveyrac", slug: "pneus-villeveyrac", distance: "35 min", axe: "A9", cp: "34560", titre: "Pneus Villeveyrac — Spécialiste Pneus Hérault", metaTitle: "Pneus Villeveyrac | Recacor Le Crès" },
  { ville: "Le Grau-du-Roi", slug: "pneus-le-grau-du-roi", distance: "35 min", axe: "A9", cp: "30240", titre: "Pneus Le Grau-du-Roi — Recacor Hérault & Gard", metaTitle: "Pneus Le Grau-du-Roi | Recacor Spécialiste" },
  { ville: "Aigues-Mortes", slug: "pneus-aigues-mortes", distance: "30 min", axe: "A9", cp: "30220", titre: "Pneus Aigues-Mortes — Garage Pneumatique", metaTitle: "Pneus Aigues-Mortes | Recacor" },
  { ville: "Saint-Gilles", slug: "pneus-saint-gilles", distance: "35 min", axe: "A9", cp: "30800", titre: "Pneus Saint-Gilles — Recacor Gard/Hérault", metaTitle: "Pneus Saint-Gilles | Recacor Le Crès" },
  { ville: "Nîmes", slug: "pneus-nimes", distance: "35 min", axe: "A9", cp: "30000", titre: "Pneus Nîmes — Garage Spécialiste Recacor", metaTitle: "Pneus Nîmes | Recacor — Spécialiste 70 ans" },
  { ville: "Sète", slug: "pneus-sete", distance: "30 min", axe: "A9", cp: "34200", titre: "Pneus Sète — Montage Rapide & Équilibrage", metaTitle: "Pneus Sète | Recacor Le Crès Hérault" },
  { ville: "Frontignan", slug: "pneus-frontignan", distance: "25 min", axe: "A9", cp: "34110", titre: "Pneus Frontignan — Recacor à 25 min", metaTitle: "Pneus Frontignan | Recacor Le Crès" },
  { ville: "Fabrègues", slug: "pneus-fabregues", distance: "25 min", axe: "A9", cp: "34690", titre: "Pneus Fabrègues — Garage Pneus Recacor", metaTitle: "Pneus Fabrègues | Recacor, Sans RDV" },
  { ville: "Montagnac", slug: "pneus-montagnac", distance: "40 min", axe: "A9", cp: "34530", titre: "Pneus Montagnac — Spécialiste Pneus Hérault", metaTitle: "Pneus Montagnac | Recacor Le Crès" },
  { ville: "Loupian", slug: "pneus-loupian", distance: "35 min", axe: "A9", cp: "34140", titre: "Pneus Loupian — Recacor Votre Garage", metaTitle: "Pneus Loupian | Recacor Hérault" },
  { ville: "Agde", slug: "pneus-agde", distance: "45 min", axe: "A9", cp: "34300", titre: "Pneus Agde — Spécialiste Pneumatique Hérault", metaTitle: "Pneus Agde | Recacor Le Crès" },
];

export const SERVICES_VL = [
  { slug: "changement-pneus-montpellier", titre: "Changement de Pneus à Montpellier — Recacor Le Crès", service: "changement de pneus", categorie: "pneus-voiture", metaTitle: "Changement Pneus Montpellier | Recacor, Dès 45€" },
  { slug: "pneus-ete-montpellier", titre: "Pneus Été Montpellier — Stock & Montage Immédiat", service: "pneus été", categorie: "pneus-voiture", metaTitle: "Pneus Été Montpellier | Recacor, En Stock" },
  { slug: "pneus-hiver-montpellier", titre: "Pneus Hiver Montpellier — Préparation & Sécurité", service: "pneus hiver", categorie: "pneus-voiture", metaTitle: "Pneus Hiver Montpellier | Recacor, Prêt en 30 min" },
  { slug: "pneus-4-saisons-montpellier", titre: "Pneus 4 Saisons Montpellier — Avantages & Prix", service: "pneus 4 saisons", categorie: "pneus-voiture", metaTitle: "Pneus 4 Saisons Montpellier | Recacor" },
  { slug: "vidange-voiture-montpellier", titre: "Vidange Voiture Montpellier — À partir de 79€", service: "vidange voiture", categorie: "mecanique", metaTitle: "Vidange Voiture Montpellier | 79€ Huile + Filtre" },
  { slug: "parallelisme-montpellier", titre: "Parallélisme & Géométrie Montpellier — Recacor", service: "parallélisme et géométrie", categorie: "mecanique", metaTitle: "Parallélisme Montpellier | 65€ + Contrôle Offert" },
  { slug: "equilibrage-pneus-montpellier", titre: "Équilibrage Pneus Montpellier — Recacor Le Crès", service: "équilibrage de pneus", categorie: "pneus-voiture", metaTitle: "Équilibrage Pneus Montpellier | Recacor" },
  { slug: "freinage-montpellier", titre: "Freinage Voiture Montpellier — Vérification & Remplacement", service: "freinage", categorie: "mecanique", metaTitle: "Freinage Voiture Montpellier | Recacor" },
  { slug: "pneus-suv-4x4-montpellier", titre: "Pneus SUV & 4x4 Montpellier — Toutes Marques", service: "pneus SUV et 4x4", categorie: "pneus-voiture", metaTitle: "Pneus SUV Montpellier | Recacor, Toutes Marques" },
  { slug: "pneus-utilitaire-montpellier", titre: "Pneus Utilitaire Montpellier — Fourgon & Van", service: "pneus utilitaires", categorie: "pneus-voiture", metaTitle: "Pneus Utilitaire Montpellier | Recacor Le Crès" },
  { slug: "pneus-run-flat-montpellier", titre: "Pneus Run-Flat Montpellier — Spécialiste Recacor", service: "pneus run-flat", categorie: "pneus-voiture", metaTitle: "Pneus Run-Flat Montpellier | Recacor" },
  { slug: "reparation-crevaison-montpellier", titre: "Réparation Crevaison Montpellier — Rapide & Efficace", service: "réparation de crevaison", categorie: "pneus-voiture", metaTitle: "Réparation Crevaison Montpellier | Recacor" },
  { slug: "stockage-pneus-montpellier", titre: "Stockage Pneus Saisonniers Montpellier — Service Recacor", service: "stockage de pneus saisonniers", categorie: "pneus-voiture", metaTitle: "Stockage Pneus Montpellier | Recacor Le Crès" },
  { slug: "revision-voiture-montpellier", titre: "Révision Voiture Montpellier — Contrôle Complet", service: "révision voiture", categorie: "mecanique", metaTitle: "Révision Voiture Montpellier | Recacor" },
  { slug: "controle-technique-montpellier", titre: "Préparation Contrôle Technique Montpellier", service: "préparation au contrôle technique", categorie: "mecanique", metaTitle: "Contrôle Technique Montpellier | Préparer sa Voiture" },
  { slug: "pneus-low-profile-montpellier", titre: "Pneus Low Profile Montpellier — Montage Expert", service: "pneus taille basse", categorie: "pneus-voiture", metaTitle: "Pneus Low Profile Montpellier | Recacor" },
  { slug: "montage-demontage-pneus", titre: "Montage & Démontage Pneus — Recacor Le Crès", service: "montage et démontage de pneus", categorie: "pneus-voiture", metaTitle: "Montage Pneus Le Crès | Recacor 45€ Monté" },
  { slug: "permutation-pneus-montpellier", titre: "Permutation Pneus Montpellier — Usure Équilibrée", service: "permutation de pneus", categorie: "pneus-voiture", metaTitle: "Permutation Pneus Montpellier | Recacor" },
  { slug: "pression-pneus-montpellier", titre: "Gonflage & Pression Pneus Montpellier", service: "gonflage et contrôle de pression", categorie: "pneus-voiture", metaTitle: "Pression Pneus Montpellier | Recacor" },
  { slug: "pneus-moto-montpellier", titre: "Pneus Moto Montpellier — Recacor Le Crès", service: "pneus moto", categorie: "pneus-voiture", metaTitle: "Pneus Moto Montpellier | Recacor Le Crès" },
];

export const MARQUES = [
  { marque: "Michelin", slug: "pneus-michelin-montpellier", titre: "Pneus Michelin à Montpellier — Prix & Disponibilité", metaTitle: "Pneus Michelin Montpellier | Recacor, En Stock" },
  { marque: "Bridgestone", slug: "pneus-bridgestone-montpellier", titre: "Pneus Bridgestone Montpellier — Recacor Spécialiste", metaTitle: "Pneus Bridgestone Montpellier | Recacor" },
  { marque: "Continental", slug: "pneus-continental-montpellier", titre: "Pneus Continental Montpellier — Stock & Prix", metaTitle: "Pneus Continental Montpellier | Recacor" },
  { marque: "Goodyear", slug: "pneus-goodyear-montpellier", titre: "Pneus Goodyear Montpellier — Recacor Le Crès", metaTitle: "Pneus Goodyear Montpellier | Recacor" },
  { marque: "Pirelli", slug: "pneus-pirelli-montpellier", titre: "Pneus Pirelli Montpellier — Toutes Dimensions", metaTitle: "Pneus Pirelli Montpellier | Recacor Le Crès" },
  { marque: "Yokohama", slug: "pneus-yokohama-montpellier", titre: "Pneus Yokohama Montpellier — Expert Recacor", metaTitle: "Pneus Yokohama Montpellier | Recacor" },
  { marque: "Hankook", slug: "pneus-hankook-montpellier", titre: "Pneus Hankook Montpellier — Qualité & Prix", metaTitle: "Pneus Hankook Montpellier | Recacor" },
  { marque: "Dunlop", slug: "pneus-dunlop-montpellier", titre: "Pneus Dunlop Montpellier — Recacor Le Crès", metaTitle: "Pneus Dunlop Montpellier | Recacor" },
  { marque: "Firestone", slug: "pneus-firestone-montpellier", titre: "Pneus Firestone Montpellier — Disponibles en Stock", metaTitle: "Pneus Firestone Montpellier | Recacor" },
  { marque: "Kumho", slug: "pneus-kumho-montpellier", titre: "Pneus Kumho Montpellier — Rapport Qualité/Prix", metaTitle: "Pneus Kumho Montpellier | Recacor" },
  { marque: "Nexen", slug: "pneus-nexen-montpellier", titre: "Pneus Nexen Montpellier — Recacor Votre Garage", metaTitle: "Pneus Nexen Montpellier | Recacor Le Crès" },
  { marque: "Falken", slug: "pneus-falken-montpellier", titre: "Pneus Falken Montpellier — Montage Rapide", metaTitle: "Pneus Falken Montpellier | Recacor" },
];

export const GUIDES_VL = [
  { slug: "quand-changer-ses-pneus", titre: "Quand Changer ses Pneus de Voiture ? Guide Complet", sujet: "quand changer ses pneus", categorie: "pneus-voiture", metaTitle: "Quand Changer ses Pneus ? Les Signes à Connaître" },
  { slug: "lire-usure-pneus", titre: "Comment Lire l'Usure de ses Pneus", sujet: "lire l'usure des pneus", categorie: "pneus-voiture", metaTitle: "Comment Lire l'Usure de ses Pneus — Guide 2025" },
  { slug: "pression-pneus-ete", titre: "Quelle Pression Pneus en Été ? Conseils Expert", sujet: "pression des pneus en été", categorie: "pneus-voiture", metaTitle: "Pression Pneus Été — Tout Savoir en 2025" },
  { slug: "pression-pneus-hiver", titre: "Pression Pneus en Hiver — Ce qu'il Faut Savoir", sujet: "pression des pneus en hiver", categorie: "pneus-voiture", metaTitle: "Pression Pneus Hiver — Conseils Expert Recacor" },
  { slug: "pneus-ete-hiver-4-saisons-comparatif", titre: "Pneus Été vs Hiver vs 4 Saisons — Lequel Choisir ?", sujet: "comparatif été / hiver / 4 saisons", categorie: "pneus-voiture", metaTitle: "Pneus Été vs Hiver vs 4 Saisons — Le Bon Choix" },
  { slug: "entretien-pneus-voiture", titre: "Comment Entretenir ses Pneus pour Durer Plus Longtemps", sujet: "entretien des pneus", categorie: "pneus-voiture", metaTitle: "Comment Entretenir ses Pneus — Guide Pratique" },
  { slug: "signes-pneus-a-changer", titre: "Les 5 Signes que vos Pneus Doivent Être Changés", sujet: "signes que les pneus sont usés", categorie: "pneus-voiture", metaTitle: "5 Signes que vos Pneus Doivent Être Changés" },
  { slug: "guide-achat-pneus-voiture", titre: "Guide d'Achat Pneus Voiture — Ne Pas Se Tromper", sujet: "guide d'achat des pneus", categorie: "pneus-voiture", metaTitle: "Guide Achat Pneus Voiture 2025 — Recacor" },
  { slug: "pneus-premium-vs-budget", titre: "Pneus Premium vs Budget — Vaut-il Mieux Payer Plus Cher ?", sujet: "premium vs budget", categorie: "pneus-voiture", metaTitle: "Pneus Premium vs Budget — Lequel Choisir ?" },
  { slug: "pneus-economie-carburant", titre: "Économiser du Carburant grâce aux Bons Pneus", sujet: "pneus et économie de carburant", categorie: "pneus-voiture", metaTitle: "Économiser du Carburant avec ses Pneus" },
  { slug: "frequence-vidange-voiture", titre: "Vidange Voiture — À Quelle Fréquence Changer l'Huile ?", sujet: "fréquence de vidange", categorie: "mecanique", metaTitle: "Quand Faire sa Vidange ? Guide Fréquence 2025" },
  { slug: "signes-mauvais-parallelisme", titre: "Parallélisme — Les Signes d'un Mauvais Réglage", sujet: "signes d'un mauvais parallélisme", categorie: "mecanique", metaTitle: "Mauvais Parallélisme — 6 Signes à Connaître" },
  { slug: "usure-asymetrique-pneus", titre: "Usure Asymétrique des Pneus — Causes & Solutions", sujet: "usure asymétrique des pneus", categorie: "pneus-voiture", metaTitle: "Usure Asymétrique Pneus — Causes et Remèdes" },
  { slug: "que-faire-crevaison", titre: "Que Faire en Cas de Crevaison ? Guide Étape par Étape", sujet: "que faire en cas de crevaison", categorie: "pneus-voiture", metaTitle: "Crevaison — Que Faire ? Guide Complet 2025" },
  { slug: "pneus-rechapes-pour-ou-contre", titre: "Pneus Rechapés — Pour ou Contre ?", sujet: "pneus rechapés", categorie: "pneus-voiture", metaTitle: "Pneus Rechapés — Avantages et Risques" },
  { slug: "tpms-surveillance-pression-pneus", titre: "TPMS — Le Système de Surveillance de Pression Expliqué", sujet: "système TPMS", categorie: "pneus-voiture", metaTitle: "TPMS — Comprendre le Voyant de Pression Pneus" },
  { slug: "pneus-directionnels-vs-asymetriques", titre: "Pneus Directionnels vs Asymétriques — Quelle Différence ?", sujet: "pneus directionnels vs asymétriques", categorie: "pneus-voiture", metaTitle: "Pneus Directionnels vs Asymétriques — Guide" },
  { slug: "montage-vs-equilibrage-pneus", titre: "Montage vs Équilibrage Pneus — Quelle Différence ?", sujet: "montage vs équilibrage", categorie: "pneus-voiture", metaTitle: "Montage vs Équilibrage — Ce qu'il Faut Savoir" },
  { slug: "changer-2-ou-4-pneus", titre: "Faut-il Changer 2 ou 4 Pneus à la Fois ?", sujet: "changer 2 ou 4 pneus", categorie: "pneus-voiture", metaTitle: "Changer 2 ou 4 Pneus — La Bonne Pratique" },
  { slug: "duree-vie-pneus", titre: "Durée de Vie des Pneus — Combien de km Avant Changement ?", sujet: "durée de vie des pneus", categorie: "pneus-voiture", metaTitle: "Durée de Vie des Pneus — Kilométrage et Conseils" },
  { slug: "stockage-pneus-saisonniers", titre: "Stockage Pneus Saisonniers — Les Bonnes Pratiques", sujet: "stockage des pneus saisonniers", categorie: "pneus-voiture", metaTitle: "Stocker ses Pneus Saisonniers — Guide 2025" },
  { slug: "choisir-pneus-hiver", titre: "Comment Choisir ses Pneus Hiver", sujet: "choix des pneus hiver", categorie: "pneus-voiture", metaTitle: "Choisir ses Pneus Hiver — Guide Expert Recacor" },
  { slug: "classement-meilleures-marques-pneus", titre: "Classement des Meilleures Marques de Pneus 2025", sujet: "meilleures marques de pneus", categorie: "pneus-voiture", metaTitle: "Top Marques Pneus 2025 — Classement Expert" },
  { slug: "roue-secours-vs-kit-anti-crevaison", titre: "Roue de Secours ou Kit Anti-Crevaison — Que Choisir ?", sujet: "roue de secours vs kit anti-crevaison", categorie: "pneus-voiture", metaTitle: "Roue de Secours vs Kit Anti-Crevaison" },
  { slug: "risques-pneus-uses", titre: "Les Risques de Rouler avec des Pneus Usés", sujet: "risques des pneus usés", categorie: "pneus-voiture", metaTitle: "Rouler avec des Pneus Usés — Dangers et Amendes" },
];

export const PL_DEPT = [
  { slug: "pneus-poids-lourd-herault", titre: "Pneus Poids Lourd Hérault (34) — Recacor Spécialiste", sujet: "pneus poids lourd dans l'Hérault", metaTitle: "Pneus PL Hérault (34) | Recacor — 70 ans d'Expert" },
  { slug: "assistance-pneus-camion-herault", titre: "Assistance Pneus Camion Hérault — Dépannage 24h/24", sujet: "assistance pneus camion 24h/24 dans l'Hérault", metaTitle: "Assistance Pneus Camion Hérault | Recacor" },
  { slug: "recreusage-pneus-pl-herault", titre: "Recreusage Pneus PL Hérault — Recacor", sujet: "recreusage de pneus poids lourd", metaTitle: "Recreusage Pneus PL Hérault | Recacor" },
  { slug: "pneus-agricoles-herault", titre: "Pneus Agricoles Hérault — Vigne, Arboriculture, Élevage", sujet: "pneus agricoles dans l'Hérault", metaTitle: "Pneus Agricoles Hérault | Recacor Spécialiste" },
  { slug: "pneus-pl-herault-vente-pose", titre: "Pneus PL Hérault — Vente, Pose & Assistance sur Site", sujet: "vente et pose de pneus PL", metaTitle: "Vente & Pose Pneus PL Hérault | Recacor" },
  { slug: "gestionnaire-flotte-herault-bilan", titre: "Gestionnaire Flotte Hérault — Bilan Pneumatique Gratuit", sujet: "bilan pneumatique gratuit pour gestionnaires de flotte", metaTitle: "Bilan Pneumatique Flotte Hérault | Recacor" },
  { slug: "pneus-industriels-herault", titre: "Pneus Industriels & Chantier Hérault — Recacor", sujet: "pneus industriels et de chantier", metaTitle: "Pneus Industriels Hérault | Recacor" },
  { slug: "pneus-pl-transport-frigorifique-herault", titre: "Transport Frigorifique Hérault — Pneus PL Adaptés", sujet: "pneus PL pour transport frigorifique", metaTitle: "Pneus PL Frigo Hérault | Recacor" },
];

export const PL_VILLES = [
  { ville: "Montpellier", slug: "pneus-camion-montpellier", distance: "10 min", titre: "Pneus Camion Montpellier — Recacor Spécialiste PL", metaTitle: "Pneus Camion Montpellier | Recacor — 70 ans" },
  { ville: "Béziers", slug: "pneus-poids-lourd-beziers", distance: "55 min", titre: "Pneus Poids Lourd Béziers — Vente & Assistance PL", metaTitle: "Pneus PL Béziers | Recacor Hérault" },
  { ville: "Narbonne", slug: "pneus-camion-narbonne", distance: "1h15", titre: "Pneus Camion Narbonne — Recacor Hérault", metaTitle: "Pneus Camion Narbonne | Recacor" },
  { ville: "Sète", slug: "pneus-sete", distance: "30 min", titre: "Pneus PL Sète — Recacor Spécialiste Hérault", metaTitle: "Pneus PL Sète | Recacor Hérault" },
  { ville: "Agde", slug: "pneus-camion-agde", distance: "45 min", titre: "Pneus Camion Agde — Recacor Le Crès", metaTitle: "Pneus Camion Agde | Recacor" },
  { ville: "Lunel", slug: "pneus-lunel", distance: "20 min", titre: "Pneus PL Lunel — Assistance & Vente Hérault", metaTitle: "Pneus PL Lunel | Recacor Hérault" },
  { ville: "Lodève", slug: "pneus-camion-lodeve", distance: "50 min", titre: "Pneus Camion Lodève — Recacor Hérault", metaTitle: "Pneus Camion Lodève | Recacor" },
  { ville: "Clermont-l'Hérault", slug: "pneus-pl-clermont-herault", distance: "45 min", titre: "Pneus PL Clermont-l'Hérault — Recacor", metaTitle: "Pneus PL Clermont-l'Hérault | Recacor" },
  { ville: "Pézenas", slug: "pneus-camion-pezenas", distance: "40 min", titre: "Pneus Camion Pézenas — Recacor Hérault", metaTitle: "Pneus Camion Pézenas | Recacor" },
  { ville: "Frontignan", slug: "pneus-pl-frontignan", distance: "25 min", titre: "Pneus PL Frontignan — Recacor Spécialiste", metaTitle: "Pneus PL Frontignan | Recacor Hérault" },
  { ville: "Mèze", slug: "pneus-camion-meze", distance: "35 min", titre: "Pneus Camion Mèze — Recacor Hérault", metaTitle: "Pneus Camion Mèze | Recacor" },
  { ville: "Lattes", slug: "pneus-pl-lattes", distance: "12 min", titre: "Pneus PL Lattes — Vente & Assistance Recacor", metaTitle: "Pneus PL Lattes | Recacor Hérault" },
  { ville: "Castelnau-le-Lez", slug: "pneus-camion-castelnau-le-lez", distance: "5 min", titre: "Pneus Camion Castelnau-le-Lez — Recacor", metaTitle: "Pneus Camion Castelnau-le-Lez | Recacor" },
  { ville: "Vendargues", slug: "pneus-pl-vendargues", distance: "5 min", titre: "Pneus PL Vendargues — Recacor Le Crès", metaTitle: "Pneus PL Vendargues | Recacor" },
  { ville: "Mauguio", slug: "pneus-camion-mauguio", distance: "10 min", titre: "Pneus Camion Mauguio — Recacor Hérault", metaTitle: "Pneus Camion Mauguio | Recacor" },
  { ville: "Saint-Jean-de-Védas", slug: "pneus-pl-saint-jean-de-vedas", distance: "15 min", titre: "Pneus PL Saint-Jean-de-Védas — Recacor", metaTitle: "Pneus PL Saint-Jean-de-Védas | Recacor" },
  { ville: "Gigean", slug: "pneus-camion-gigean", distance: "30 min", titre: "Pneus Camion Gigean — Recacor Hérault", metaTitle: "Pneus Camion Gigean | Recacor" },
  { ville: "Montagnac", slug: "pneus-pl-montagnac", distance: "40 min", titre: "Pneus PL Montagnac — Recacor Hérault", metaTitle: "Pneus PL Montagnac | Recacor" },
  { ville: "Servian", slug: "pneus-camion-servian", distance: "1h", titre: "Pneus Camion Servian — Recacor", metaTitle: "Pneus Camion Servian | Recacor" },
  { ville: "Le Crès", slug: "pneus-pl-le-cres", distance: "0 min — sur place", titre: "Pneus PL Le Crès — Garage Recacor sur Place", metaTitle: "Pneus PL Le Crès | Recacor — Garage sur Place" },
  { ville: "Lunel-Viel", slug: "pneus-camion-lunel-viel", distance: "18 min", titre: "Pneus Camion Lunel-Viel — Recacor Hérault", metaTitle: "Pneus Camion Lunel-Viel | Recacor" },
  { ville: "Côte héraultaise", slug: "pneus-pl-palavas-cote-heraultaise", distance: "20 min", titre: "Pneus PL Palavas & Côte Héraultaise — Recacor", metaTitle: "Pneus PL Côte Héraultaise | Recacor" },
];

export const GUIDES_PL = [
  { slug: "recreusage-pneus-poids-lourd", titre: "Recreusage Pneus Poids Lourd — Guide Complet", sujet: "recreusage des pneus poids lourd", metaTitle: "Recreusage Pneus PL — Économies et Réglementation" },
  { slug: "assistance-pneus-pl-24h", titre: "Assistance Pneus PL 24h/24 — Comment Ça Fonctionne", sujet: "assistance pneus PL 24h/24", metaTitle: "Assistance Pneus PL 24h | Recacor — Dépannage" },
  { slug: "pneus-agricoles-guide", titre: "Pneus Agricoles — Guide d'Achat Complet", sujet: "achat de pneus agricoles", metaTitle: "Pneus Agricoles — Guide d'Achat 2025 Recacor" },
  { slug: "pneus-industriels", titre: "Pneus Industriels — Choisir pour son Chantier", sujet: "choix de pneus industriels pour chantier", metaTitle: "Pneus Industriels — Recacor Spécialiste" },
  { slug: "reglementation-pneus-poids-lourd", titre: "Réglementation Pneus Poids Lourd en France 2025", sujet: "réglementation des pneus PL en 2025", metaTitle: "Réglementation Pneus PL 2025" },
  { slug: "entretien-pneumatiques-flotte-pl", titre: "Entretien Pneumatiques Flotte Poids Lourds", sujet: "entretien d'une flotte de pneus PL", metaTitle: "Entretien Pneus Flotte PL — Guide Gestionnaire" },
  { slug: "optimiser-couts-pneumatiques-transport", titre: "Optimiser ses Coûts Pneumatiques en Transport", sujet: "optimisation des coûts pneumatiques en transport", metaTitle: "Réduire les Coûts Pneus PL — Stratégie Transport" },
  { slug: "pneus-pl-hiver-reglementation", titre: "Pneus PL Hiver — Réglementation & Obligations 2025", sujet: "réglementation hivernale pour pneus PL", metaTitle: "Pneus PL Hiver 2025 — Obligations Transporteurs" },
  { slug: "depannage-poids-lourd-route", titre: "Dépannage Poids Lourd sur Route — Procédure Complète", sujet: "dépannage PL sur route", metaTitle: "Dépannage PL sur Route — Que Faire ?" },
  { slug: "gestion-flotte-pneumatique", titre: "Gestion Flotte Transport — Le Pneumatique au Cœur du Budget", sujet: "gestion pneumatique d'une flotte transport", metaTitle: "Gestion Flotte PL — Optimiser son Budget Pneus" },
  { slug: "recreusage-vs-neuf-pl", titre: "Recreusage vs Pneu Neuf PL — Le Vrai Comparatif", sujet: "recreusage vs pneu neuf PL", metaTitle: "Recreusage vs Neuf PL — Analyse Coût/Durée" },
  { slug: "profondeur-legale-pneus-pl", titre: "Profondeur Minimale Légale des Pneus PL", sujet: "profondeur légale des pneus PL", metaTitle: "Profondeur Légale Pneus PL — Réglementation 2025" },
  { slug: "montage-pneus-pl-sur-site", titre: "Montage Pneus PL sur Site — Comment Ça Marche", sujet: "montage de pneus PL sur site", metaTitle: "Montage Pneus PL sur Site | Recacor" },
  { slug: "meilleures-marques-pneus-pl", titre: "Pneus Poids Lourd — Les Meilleures Marques 2025", sujet: "meilleures marques de pneus PL", metaTitle: "Top Marques Pneus PL 2025 — Comparatif Expert" },
  { slug: "surveillance-pression-pneus-pl", titre: "Surveillance Pression Pneus PL — Technologies 2025", sujet: "surveillance de la pression des pneus PL", metaTitle: "TPMS PL — Technologies de Surveillance Pression" },
  { slug: "formation-conducteur-pl-controle-pneus", titre: "Formation Conducteur PL — Contrôler ses Pneus avant Départ", sujet: "contrôle des pneus avant départ pour conducteurs PL", metaTitle: "Formation PL — Contrôle Pneus avant Départ" },
  { slug: "super-single-vs-double-monte-pl", titre: "Pneus Super Single vs Double Monte PL", sujet: "super single vs double monte sur PL", metaTitle: "Super Single vs Double Monte PL — Avantages" },
  { slug: "bilan-pneumatique-flotte", titre: "Bilan Pneumatique Flotte — Diagnostic Gratuit Recacor", sujet: "bilan pneumatique d'une flotte", metaTitle: "Bilan Pneus Flotte PL — Diagnostic Gratuit" },
];

export const FAQS = [
  { slug: "cout-pneu-monte-montpellier", titre: "Combien Coûte un Pneu Monté à Montpellier ?", sujet: "coût d'un pneu monté à Montpellier", metaTitle: "Prix Pneu Monté Montpellier | Recacor, dès 45€" },
  { slug: "rendez-vous-recacor-le-cres", titre: "Faut-il Prendre Rendez-vous chez Recacor Le Crès ?", sujet: "rendez-vous chez Recacor", metaTitle: "Recacor Le Crès — Sans Rendez-vous, Accueil Direct" },
  { slug: "garage-vs-centre-auto", titre: "Garage vs Centre Auto — Quelle Différence ?", sujet: "différence entre garage et centre auto", metaTitle: "Garage vs Centre Auto — Où Aller pour ses Pneus ?" },
  { slug: "pneus-low-cost-fiabilite", titre: "Peut-on Faire Confiance aux Pneus Low-Cost ?", sujet: "fiabilité des pneus low-cost", metaTitle: "Pneus Low-Cost — Fiables ou Dangereux ?" },
  { slug: "devis-pneus-en-ligne", titre: "Comment Obtenir un Devis Pneus en Ligne ?", sujet: "devis pneus en ligne", metaTitle: "Devis Pneus en Ligne | Recacor — Réponse en 2h" },
  { slug: "histoire-recacor", titre: "Recacor — Qui Sont-ils et Quelle est Leur Histoire ?", sujet: "histoire de Recacor depuis 1950", metaTitle: "Recacor — 70 ans d'Expertise Pneumatique" },
  { slug: "controle-parallelisme-offert", titre: "Pourquoi le Contrôle Parallélisme est Offert chez Recacor ?", sujet: "contrôle parallélisme offert", metaTitle: "Contrôle Parallélisme Offert | Recacor Le Crès" },
  { slug: "huile-synthetique-vs-minerale", titre: "Vidange — Huile Synthétique ou Minérale ?", sujet: "huile synthétique vs minérale", metaTitle: "Vidange — Synthétique ou Minérale ? Guide 2025" },
  { slug: "pneu-reparable-ou-a-remplacer", titre: "Mon Pneu est-il Réparable ou Doit-il Être Remplacé ?", sujet: "pneu réparable ou à remplacer", metaTitle: "Pneu Réparable ou à Changer — Comment Savoir ?" },
  { slug: "quand-faire-parallelisme", titre: "Quand Faire son Parallélisme ?", sujet: "quand faire son parallélisme", metaTitle: "Quand Faire son Parallélisme — Fréquence & Signes" },
  { slug: "duree-changement-pneus", titre: "Combien de Temps Dure un Changement de Pneus ?", sujet: "durée d'un changement de pneus", metaTitle: "Changement de Pneus — Combien de Temps ?" },
  { slug: "melanger-marques-pneus", titre: "Peut-on Mélanger des Marques de Pneus sur sa Voiture ?", sujet: "mélanger des marques de pneus", metaTitle: "Mélanger des Marques de Pneus — Risque ou Non ?" },
  { slug: "indice-vitesse-pneus", titre: "Quel Indice de Vitesse pour mes Pneus ?", sujet: "indice de vitesse des pneus", metaTitle: "Indice de Vitesse Pneus — Guide Complet 2025" },
  { slug: "lire-dimensions-pneu", titre: "Comment Lire les Chiffres sur un Pneu (225/45R17) ?", sujet: "lire les dimensions d'un pneu", metaTitle: "Lire les Dimensions d'un Pneu — Guide Pratique" },
  { slug: "pourquoi-choisir-recacor", titre: "Recacor vs Autres Garages — Pourquoi Nous Choisir ?", sujet: "pourquoi choisir Recacor", metaTitle: "Recacor Le Crès — Ce qui Nous Différencie" },
];

export const SAISONNIERS = [
  { slug: "pneus-hiver-2025-herault", titre: "Passer aux Pneus Hiver 2025 — Ce qu'il Faut Savoir en Hérault", sujet: "passage aux pneus hiver 2025 dans l'Hérault", metaTitle: "Pneus Hiver 2025 Hérault | Recacor Le Crès" },
  { slug: "pneus-ete-2025-montpellier", titre: "Pneus Été 2025 — Les Meilleures Offres à Montpellier", sujet: "pneus été 2025 à Montpellier", metaTitle: "Pneus Été 2025 Montpellier | Recacor" },
  { slug: "pneus-chaleur-ete-sud", titre: "Chaleur & Pneus — Les Risques de l'Été dans le Sud", sujet: "effets de la chaleur sur les pneus", metaTitle: "Pneus et Chaleur — Risques et Précautions Été" },
  { slug: "preparer-voiture-vacances-ete", titre: "Préparer sa Voiture avant les Vacances d'Été", sujet: "préparation voiture pour les vacances d'été", metaTitle: "Préparer sa Voiture pour les Vacances — Checklist" },
  { slug: "pneus-securite-fetes", titre: "Pneus et Sécurité Routière pour les Fêtes de Fin d'Année", sujet: "pneus et sécurité routière en fin d'année", metaTitle: "Pneus — Sécurité Routière pour les Fêtes 2025" },
  { slug: "loi-montagne-2025-herault", titre: "Loi Montagne 2025 — Êtes-vous Concernés dans l'Hérault ?", sujet: "loi montagne 2025 dans l'Hérault", metaTitle: "Loi Montagne 2025 — Hérault et Régions Concernées" },
  { slug: "canicule-effets-pneus", titre: "Canicule — Quels Effets sur vos Pneus ?", sujet: "effets de la canicule sur les pneus", metaTitle: "Canicule et Pneus — Les Précautions à Prendre" },
  { slug: "pluie-aquaplaning-meilleurs-pneus", titre: "Pluie & Aquaplaning — Les Pneus qui Protègent le Mieux", sujet: "pluie, aquaplaning et choix des pneus", metaTitle: "Aquaplaning — Quels Pneus Choisir pour la Pluie ?" },
  { slug: "controle-technique-2025-pneus", titre: "Contrôle Technique 2025 — Les Points sur les Pneus", sujet: "points de contrôle pneus au CT 2025", metaTitle: "CT 2025 — Les Points de Contrôle sur les Pneus" },
  { slug: "embouteillages-montpellier-pneus", titre: "Embouteillages Montpellier — Impact sur vos Pneus", sujet: "impact des embouteillages sur les pneus", metaTitle: "Trafic Montpellier — Comment ça Use vos Pneus" },
  { slug: "pneus-promo-conseils", titre: "Pneus en Promotion — Comment Ne Pas Se Faire Piéger", sujet: "promotions pneus et pièges à éviter", metaTitle: "Pneus en Promo — Les Pièges à Éviter" },
  { slug: "black-friday-pneus", titre: "Black Friday Pneus — Bons Plans ou Arnaques ?", sujet: "Black Friday et achat de pneus", metaTitle: "Black Friday Pneus — Bons Plans ou Pièges ?" },
  { slug: "preparer-voiture-ete-2025", titre: "Été 2025 — Préparer sa Voiture pour Partir en Vacances", sujet: "préparation voiture été 2025", metaTitle: "Préparer sa Voiture Été 2025 — Checklist Recacor" },
  { slug: "verifier-voiture-rentree-2025", titre: "Rentrée 2025 — Vérifier son Véhicule avant les Trajets Quotidiens", sujet: "vérification du véhicule à la rentrée", metaTitle: "Rentrée 2025 — Vérifier sa Voiture en 10 Points" },
  { slug: "bon-revision-voiture-noel", titre: "Noël — Offrir un Bon de Révision Auto à ses Proches", sujet: "bon cadeau révision auto pour Noël", metaTitle: "Bon de Révision Auto — Idée Cadeau Noël Recacor" },
  { slug: "reduire-couts-transport-pneus", titre: "Hausse Coûts Transport — Réduire la Facture Pneumatique PL", sujet: "réduction des coûts pneumatiques en transport", metaTitle: "Réduire Coûts Pneus PL — Stratégie 2025" },
  { slug: "recacor-ouvre-le-cres", titre: "Recacor Ouvre ses Portes à Le Crès — Bienvenue !", sujet: "ouverture du garage Recacor Le Crès", metaTitle: "Recacor Le Crès — Votre Nouveau Spécialiste Pneus" },
  { slug: "recacor-70-ans-expertise", titre: "Recacor — Plus de 70 ans d'Expertise Pneumatique", sujet: "expertise Recacor depuis 1950", metaTitle: "Recacor — 70 ans d'Expertise Pneus depuis 1950" },
  { slug: "recacor-le-cres-garage-confiance", titre: "Recacor Le Crès — Votre Garage Pneus de Confiance", sujet: "Recacor Le Crès, garage de confiance", metaTitle: "Recacor Le Crès — Garage Pneus de Confiance" },
  { slug: "tendances-pneumatiques-2025", titre: "Tendances Pneumatiques 2025 — Ce qui Change pour les Pros", sujet: "tendances pneumatiques 2025 pour les professionnels", metaTitle: "Tendances Pneus 2025 — Ce qui Change pour les PL" },
];
